SCRIPTS=	opnsense.sh opnsense-geoip.sh opnsense-hostname.sh opnsense-import.sh \
		opnsense-install.sh opnsense-license.sh opnsense-reset.sh \
		opnsense-rootpass.sh opnsense-ufs.sh opnsense-zfs.sh opnsense.subr.sh

MAN=		# not needed

PREFIX?=${DESTDIR}/usr

BINDIR=	${PREFIX}/libexec/bsdinstall

.include <bsd.prog.mk>
